# Generated by Django 4.0.5 on 2022-08-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_produto_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastro_Usuario',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='cidade',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
